//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public Nullable<bool> Confirmed { get; set; }
    }
}
